### ISSUE TITLE
What is the version number of bear applicable to PVS?

### ISSUE THREAD

**Issue by tr4v3ler** [viva64/pvs-studio-makefile-examples#2]
Since the output format of bear is changing all the time, PVS will encounter errors when parsing JSON output files of some bear versions. Can you give me a specific available bear version number? The PVs version I use is 7.14.50353.142 and the bear version is 2.3.11.

**Comment by Minatych** [comment]
Hi tr4v3ler.
Sorry for delay.

Can you please send the generated 'compile_commands.json' for better diagnostics?
For now, you can try the [compiledb]( https://github.com/nickdiego/compiledb) utility.

**Comment by Minatych** [comment]
Hi @tr4v3ler.

We have tested 'bear' version [2.4](https://repology.org/repository/ubuntu_20_04) and higher. Try to use them, or [compiledb](https://github.com/nickdiego/compiledb).
The 2.3.11 version doesn't work.
